FROM node:alpine AS base
WORKDIR /app
ENV NODE_ENV=production
EXPOSE 5003

FROM node:alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

FROM base AS final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT [ "node", "index.js"]