version: '3.4'

services:
  database:
    image: mysql
    deploy:
      replicas: 3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
    - ./Database/init:/docker-entrypoint-initdb.d
    networks:
    - network
    security_opt:
      - seccomp:unconfined
    # command: --secure-file-priv=""
    ports:
      - "3306:3306"
  
  posts_service:
    image: 127.0.0.1:5000/posts_service:latest
    build: .
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: ${MYSQL_DOCKER_SERVICE_NAME}
    volumes:
      - ./PostsService/PostsService:/app
    networks:
      - network
    expose:
      - "5000"

      
networks:
  network: