version: '3.4'

services:
  database-1:
    image: locchat/database
    deploy:
      replicas: 1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
    - network
    security_opt:
      - seccomp:unconfined
    # command: --secure-file-priv=""
    expose:
      - "3306"

  database-2:
    image: locchat/database
    deploy:
      replicas: 1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
    - network
    security_opt:
      - seccomp:unconfined
    # command: --secure-file-priv=""
    expose:
      - "3306"
  
  # comments_service:
  #   image: locchat/commentsservice:latest
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_HOST: ${SWARM_STACK_NAME}_${MYSQL_DOCKER_SERVICE_NAME}

  #   networks:
  #     - network
  #   ports:
  #     - "5000:5000"

  trending_posts_service:
    image: locchat/trendingpostsservice:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: ${SWARM_STACK_NAME}_${MYSQL_DOCKER_SERVICE_NAME}
    networks:
      - network
    ports:
      - "5001:5000"
networks:
  network: