FROM mcr.microsoft.com/dotnet/sdk:5.0

WORKDIR /Models
COPY Models/*.csproj ./
RUN dotnet restore

COPY Models/. ./

WORKDIR ../app
COPY PostsService/*.csproj ./
RUN dotnet restore

COPY PostsService/. ./

EXPOSE 5000
CMD ["dotnet", "watch", "run"];