FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env

WORKDIR /Models
COPY Models/*.csproj ./
RUN dotnet restore

COPY Models/. ./

WORKDIR ../app
COPY CommentsService/*.csproj ./
RUN dotnet restore

COPY CommentsService/. ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/sdk:5.0
WORKDIR /app
COPY --from=build-env /app/out .
EXPOSE 5000
ENTRYPOINT ["dotnet", "CommentsService.dll"]